# Generated by Django 5.0.6 on 2024-08-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now_add=True)),
                ("Activity_name", models.CharField(max_length=50)),
                ("Activity", models.CharField(max_length=1000)),
                ("file", models.FileField(upload_to="uploads/")),
                ("photo", models.ImageField(upload_to="myimage/")),
            ],
        ),
    ]
