# Generated by Django 5.0.6 on 2024-08-12 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity_model",
            old_name="photo",
            new_name="image",
        ),
    ]
