# Generated by Django 5.0.6 on 2024-08-17 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0004_activity_model_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activity_model",
            table="Activity_model",
        ),
    ]
