# Generated by Django 5.0.6 on 2024-08-17 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0005_alter_activity_model_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activity_model",
            table="activity_model",
        ),
    ]
